# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Quiz',
        ),
    ]
