# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-02 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_answer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quizNum',
            field=models.IntegerField(default=0),
        ),
    ]
